apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-do-luks-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-luks-block-storage
